name: Daily Green Commit 🌱

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make a dummy commit
        run: |
          echo "Green Square: $(date)" >> commit.md
          git config user.name "AkshSurani"
          git config user.email "akshsurani16@gmail.com"
          git add .
          git commit -m "Daily green square"
      - name: Push changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/AkshSurani/green-squares.git
          git push origin main
