name: Daily commit

on:
  schedule:
    - cron: '0 10 * * *' # Every day at 10 AM UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make a dummy commit
        run: |
          echo "Green Square: $(date)" >> commit.md
          git config --global user.email "akshsurani16@gmail.com"
          git config --global user.name "AkshSurani"
          git add .
          git commit -m "Daily green square"
          git push
